"""Build the koe desktop application.

    python packaging/build.py                 # full build
    python packaging/build.py --no-japanese   # smaller, character segmentation
    python packaging/build.py --installer     # also produce Setup.exe
    python packaging/build.py --installer --version 0.1.30 --manifest
                                              # a release: stamped, with latest.json

Does four things a bare `pyinstaller` invocation does not:

**Derives the version from one place.** The Windows version resource and the
installer script both restate the version, and a second hand-maintained copy of
a version number is a copy that goes stale.

**Builds the web client first.** The bundle is committed, but rebuilding here
means a packaged app can never ship a stale UI — the failure that produces a
bug report about a fix made weeks ago.

**Verifies the artifact.** A PyInstaller build succeeds happily while producing
an executable that dies on launch from a missing hidden import. The build is
not finished until the thing has been started and has served a real request.

**Reports what it produced.** Size is a real property of a desktop app, and one
that quietly triples when a dependency is added.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING = ROOT / "packaging"
DIST = ROOT / "dist"
BUILD = ROOT / "build"
APP_DIR = DIST / "koe"
APP_EXE = APP_DIR / "koe.exe"
BUILD_INFO = PACKAGING / "build_info.json"
MANIFEST = DIST / "latest.json"
REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "jon-jc/koe-harness")
VERSION_PATTERN = re.compile(r"\d+\.\d+\.\d+")

VERSION_FIELDS = [
    ("CompanyName", "jon-jc"),
    ("FileDescription", "koe - bilingual voice AI harness"),
    ("InternalName", "koe"),
    ("LegalCopyright", "MIT License"),
    ("OriginalFilename", "koe.exe"),
    ("ProductName", "koe"),
]

# Japanese (ja-JP) first, then English (en-US), both Unicode. A Japanese
# Windows install reads the ja-JP table and shows the properties in place.
LANGUAGE_CODES = ("041104b0", "040904b0")


def _inno_candidates() -> list[Path]:
    """Where ISCC.exe might be.

    winget installs Inno Setup per-user by default, which puts it under
    LOCALAPPDATA rather than Program Files — a location most build scripts
    miss, and then report the compiler as absent on a machine that has it.
    """
    paths = [
        Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"),
        Path(r"C:\Program Files\Inno Setup 6\ISCC.exe"),
    ]
    local = os.environ.get("LOCALAPPDATA")
    if local:
        paths.append(Path(local) / "Programs" / "Inno Setup 6" / "ISCC.exe")
    found = shutil.which("ISCC")
    if found:
        paths.insert(0, Path(found))
    return paths


def run(command: list[str], *, cwd: Path | None = None, env: dict[str, str] | None = None) -> None:
    printable = " ".join(command)
    print(f"\n$ {printable}", flush=True)
    result = subprocess.run(command, cwd=cwd, env=env, check=False)
    if result.returncode != 0:
        raise SystemExit(f"command failed ({result.returncode}): {printable}")


# --------------------------------------------------------------------------
# version
# --------------------------------------------------------------------------


def project_version() -> str:
    """Read the version from pyproject, so there is a single source of it."""
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version = "([^"]+)"', text, re.M)
    if not match:
        raise SystemExit("could not find a version in pyproject.toml")
    return match.group(1)


def write_version_resource(version: str) -> None:
    """Generate the Windows version resource embedded in koe.exe.

    Generated rather than committed because it restates the version. Without
    it the file-properties dialog shows a blank publisher, which is exactly
    what an unsigned binary from an unknown source looks like — and this one is
    already unsigned.
    """
    parts = [int(p) for p in version.split(".")] + [0, 0, 0, 0]
    quad = ", ".join(str(p) for p in parts[:4])

    fields = [*VERSION_FIELDS, ("FileVersion", version), ("ProductVersion", version)]
    entries = ",\n         ".join(f'StringStruct("{k}", "{v}")' for k, v in sorted(fields))
    tables = ",\n      ".join(
        f'StringTable(\n        "{code}",\n        [{entries}])' for code in LANGUAGE_CODES
    )

    content = (
        "# Generated by packaging/build.py - do not edit.\n"
        "VSVersionInfo(\n"
        "  ffi=FixedFileInfo(\n"
        f"    filevers=({quad}),\n"
        f"    prodvers=({quad}),\n"
        "    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)\n"
        "  ),\n"
        "  kids=[\n"
        "    StringFileInfo([\n"
        f"      {tables}\n"
        "    ]),\n"
        '    VarFileInfo([VarStruct("Translation", [1041, 1200, 1033, 1200])])\n'
        "  ]\n"
        ")\n"
    )
    (PACKAGING / "version_info.txt").write_text(content, encoding="utf-8")


def resolve_version(explicit: str | None) -> str:
    """The version to stamp: explicit, then ``KOE_BUILD_VERSION``, then pyproject.

    Releases are numbered per merge (see ``.github/workflows/release.yml``),
    which pyproject cannot know, so CI passes the number in. A local build
    keeps the pyproject version — lower than any release — so an installed
    developer build is still offered the next published one.
    """
    version = explicit or os.environ.get("KOE_BUILD_VERSION") or project_version()
    if not VERSION_PATTERN.fullmatch(version):
        raise SystemExit(f"version {version!r} is not MAJOR.MINOR.PATCH")
    return version


def git_commit() -> str:
    if os.environ.get("GITHUB_SHA"):
        return os.environ["GITHUB_SHA"]
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=False
        )
    except OSError:
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def write_build_info(version: str) -> None:
    """Stamp what this build is into the bundle, for the updater to compare.

    Without it, every build would report the pyproject version, and an updater
    comparing identical numbers can never tell a newer release from this one.
    """
    info = {
        "version": version,
        "commit": git_commit(),
        "channel": os.environ.get("KOE_BUILD_CHANNEL", "local"),
        "built_at": datetime.now(UTC).isoformat(timespec="seconds"),
    }
    BUILD_INFO.write_text(json.dumps(info, indent=2) + "\n", encoding="utf-8")
    print(f"  build info: {info['channel']} {version} {info['commit'][:7]}")


def write_manifest(installer: Path, digest: str, version: str) -> Path:
    """Write ``latest.json``: what installed copies read to find this release.

    The URL is where the release workflow publishes the installer. The updater
    refuses an installer URL that is not this repository's releases, so the
    manifest cannot be pointed somewhere else without being rejected.
    """
    tag = f"v{version}"
    manifest = {
        "version": version,
        "tag": tag,
        "commit": git_commit(),
        "published_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "notes_url": f"https://github.com/{REPOSITORY}/releases/tag/{tag}",
        "installer": {
            "name": installer.name,
            "url": f"https://github.com/{REPOSITORY}/releases/download/{tag}/{installer.name}",
            "sha256": digest,
            "size": installer.stat().st_size,
        },
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return MANIFEST


# --------------------------------------------------------------------------
# build steps
# --------------------------------------------------------------------------


def build_web() -> None:
    """Rebuild the browser bundle so the app cannot ship a stale UI."""
    npm = shutil.which("npm")
    if npm is None:
        print("! npm not found - using the committed web/dist bundle")
        if not (ROOT / "web" / "dist" / "app.js").exists():
            raise SystemExit("no committed bundle and no npm; cannot continue")
        return
    web = ROOT / "web"
    if not (web / "node_modules").is_dir():
        run([npm, "ci", "--no-audit", "--no-fund"], cwd=web)
    run([npm, "run", "build"], cwd=web)


def build_app(*, with_japanese: bool, clean: bool) -> None:
    env = dict(os.environ)
    env["KOE_BUILD_JAPANESE"] = "1" if with_japanese else "0"

    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        str(PACKAGING / "koe.spec"),
        "--noconfirm",
        "--distpath",
        str(DIST),
        "--workpath",
        str(BUILD),
    ]
    if clean:
        command.append("--clean")
    run(command, cwd=ROOT, env=env)


def directory_size(path: Path) -> int:
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file())


def verify() -> None:
    """Start the built app headless and confirm it serves real requests.

    A frozen build fails at *import* time far more often than at build time —
    a missing hidden import produces a perfectly successful build and an
    executable that closes instantly. Catching that here rather than from a
    user is the entire point of this step.
    """
    if not APP_EXE.exists():
        raise SystemExit(f"expected {APP_EXE} to exist")

    print("\n-- verifying the built application --", flush=True)
    env = dict(os.environ)
    env["KOE_DESKTOP_HEADLESS"] = "1"  # start the server, skip the window
    port_file = BUILD / "port.txt"
    env["KOE_DESKTOP_PORT_FILE"] = str(port_file)
    port_file.unlink(missing_ok=True)

    process = subprocess.Popen(
        [str(APP_EXE)],
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    try:
        port: int | None = None
        for _ in range(900):  # up to 90s; a cold first run unpacks a lot
            if port_file.exists():
                try:
                    port = int(port_file.read_text(encoding="utf-8").strip())
                    break
                except ValueError:
                    pass
            if process.poll() is not None:
                output = process.stdout.read() if process.stdout else ""
                raise SystemExit(f"the application exited during startup:\n{output}")
            time.sleep(0.1)

        if port is None:
            raise SystemExit("the application never reported a port")

        try:
            with urllib.request.urlopen(f"http://127.0.0.1:{port}/health", timeout=20) as response:
                body = json.loads(response.read())
        except (urllib.error.URLError, TimeoutError) as exc:
            raise SystemExit(f"health check failed: {exc}") from exc

        print(f"   health:   {body['status']}   japanese: {body['japanese_tokenizer']}")
        if body["status"] != "ok":
            raise SystemExit(f"unhealthy: {body}")

        # Exercise the real pipeline, not just the health endpoint. A bundle
        # can be healthy and still be missing the corpus or the dictionary.
        request = urllib.request.Request(
            f"http://127.0.0.1:{port}/v1/transcribe",
            data=json.dumps({"meeting": "quarterly-ja", "priority": "quality"}).encode(),
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(request, timeout=30) as response:
            transcript = json.loads(response.read())
        segments = len(transcript.get("segments", []))
        if segments == 0:
            raise SystemExit("the bundled pipeline produced no segments")
        print(f"   pipeline: {segments} segments via {transcript['routed_to']}")

        # And fetch the page the window will actually show. This check exists
        # because its absence shipped: the resource path was wrong for a frozen
        # build, so `/` served the "build the client" placeholder while every
        # check above passed. A binary that answers /health is not a binary
        # that runs the product.
        with urllib.request.urlopen(f"http://127.0.0.1:{port}/", timeout=20) as response:
            page = response.read().decode("utf-8", "replace")
        if "Build the client" in page or 'id="toggle"' not in page:
            raise SystemExit(
                "the bundle serves the placeholder page, not the web client — "
                "the client is missing from the bundle or _web_root() is wrong"
            )

        # The bundle is served from /static; a 200 on the page with a 404 on
        # its script is the same failure one layer down.
        with urllib.request.urlopen(f"http://127.0.0.1:{port}/static/app.js", timeout=20) as res:
            script_bytes = len(res.read())
        if script_bytes < 1000:
            raise SystemExit(f"/static/app.js is {script_bytes} bytes; the bundle is not there")
        print(f"   client:   index.html + app.js ({script_bytes / 1024:,.0f} KB)")
    finally:
        process.terminate()
        try:
            process.wait(timeout=15)
        except subprocess.TimeoutExpired:
            process.kill()


def build_installer(version: str) -> Path | None:
    """Compile the Inno Setup installer, if the compiler is present.

    The version is passed as a define rather than written into ``koe.iss``, so
    a release build does not leave the working tree modified.
    """
    compiler = next((p for p in _inno_candidates() if p.exists()), None)
    if compiler is None:
        print(
            "\n! Inno Setup 6 not found - skipping the installer.\n"
            "  Install it (winget install JRSoftware.InnoSetup) and re-run\n"
            "  with --installer, or ship dist/koe as a portable folder."
        )
        return None
    run([str(compiler), f"/DAppVersion={version}", str(PACKAGING / "koe.iss")], cwd=ROOT)
    produced = DIST / f"koe-setup-{version}.exe"
    return produced if produced.exists() else None


def write_checksum(target: Path) -> str:
    """Write `SHA256SUMS.txt` beside `target` and return the digest.

    The installer is unsigned — a code-signing certificate is a recurring cost
    this project does not carry — so Windows will show a SmartScreen warning on
    a downloaded copy. A published digest is what turns "trust me" into
    something a user can actually check before they click through it, and it is
    the only integrity guarantee an unsigned binary has.
    """
    digest = hashlib.sha256(target.read_bytes()).hexdigest()
    # `sha256sum -c` / `Get-FileHash` format: digest, two spaces, bare name.
    (target.parent / "SHA256SUMS.txt").write_text(f"{digest}  {target.name}\n", encoding="utf-8")
    return digest


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the koe desktop application")
    parser.add_argument(
        "--no-japanese",
        action="store_true",
        help="exclude MeCab/unidic (~248MB smaller; character segmentation instead)",
    )
    parser.add_argument("--installer", action="store_true", help="also build Setup.exe")
    parser.add_argument("--skip-web", action="store_true", help="use the committed bundle")
    parser.add_argument("--skip-verify", action="store_true", help="do not launch the result")
    parser.add_argument("--clean", action="store_true", help="discard PyInstaller caches")
    parser.add_argument(
        "--version", help="version to stamp (default: KOE_BUILD_VERSION, pyproject)"
    )
    parser.add_argument(
        "--manifest", action="store_true", help="also write dist/latest.json for the updater"
    )
    args = parser.parse_args()

    if sys.platform != "win32":
        print(f"! building on {sys.platform}; the .exe target is Windows-only")

    started = time.time()

    version = resolve_version(args.version)
    print(f"building koe {version}")
    write_version_resource(version)
    write_build_info(version)

    if not args.skip_web:
        build_web()

    build_app(with_japanese=not args.no_japanese, clean=args.clean)

    if not args.skip_verify:
        verify()

    size_mb = directory_size(APP_DIR) / 1024 / 1024
    print("\n" + "=" * 66)
    print(f"  built  {APP_EXE}")
    print(f"  size   {size_mb:,.0f} MB  (japanese: {'no' if args.no_japanese else 'yes'})")
    print(f"  took   {time.time() - started:,.0f}s")

    if args.installer:
        installer = build_installer(version)
        if installer:
            digest = write_checksum(installer)
            print(f"  setup  {installer}  ({installer.stat().st_size / 1024 / 1024:,.0f} MB)")
            print(f"  sha256 {digest}")
            if args.manifest:
                print(f"  feed   {write_manifest(installer, digest, version)}")
        elif args.manifest:
            raise SystemExit("--manifest needs an installer, and none was built")
    print("=" * 66)
    return 0


if __name__ == "__main__":
    sys.exit(main())
